# List of environment configurations.
# You may need to use `winget install --id Python.Python.3.12` first.
# You may need to use https://mirrors.ustc.edu.cn/ if something wrong with downloading.

# Python third-party libraries that need to be installed/upgraded.
libraries = [
    'numpy',
    'scipy',
    'sympy',

    'matplotlib',
    'pillow',     # PIL
    # 'jupyter',

    'pyinstaller',
    'pygame',
    'pyautogui',
    'pyserial',    # serial

    # 'wordcloud',
    # 'jieba',

    'requests',
    'beautifulsoup4', # bs4

    'opencv-python', # cv2, name conflicts with easyocr's dep: opencv-python-headless
    # 'tensorflow', # the latest version conflicts with numpy

    'autopep8',
    'ipython',

    'colorama',
    'tqdm',

    'PySide6',

    'graph-tools',
    'objprint',
    'viztracer',

    'django',
    'djlint',
]

# Applications that need to be installed.
#
# name = the name of the application.
# method = one of ['automatic', 'manual', 'winget'].
# - automatic = automatically download and try automatic installation.
#   - url = the URL download the file directly.
#   - args = install arguments.
# - manual = manual download and installation.
#   - site = the download site at which the browser opens.
# - winget = download and install using winget.
#   - id = the ID of the application in winget.

[[applications]]
name = 'Qt'
method = 'automatic'
url = 'https://mirror.nju.edu.cn/qt/official_releases/online_installers/qt-unified-windows-x64-online.exe'
args = '--mirror https://mirror.nju.edu.cn/qt'

[[applications]]
name = 'Sublime Text'
method = 'winget'
id = 'SublimeHQ.SublimeText.4'

[[applications]]
name = 'Bandizip'
method = 'winget'
id = 'Bandisoft.Bandizip'

[[applications]]
name = 'Android Studio'
method = 'winget'
id = 'Google.AndroidStudio'

[[applications]]
name = 'Git'
method = 'winget'
id = 'Git.Git'

[[applications]]
name = 'Sourcetrail'
method = 'manual'
site = 'https://github.com/CoatiSoftware/Sourcetrail/releases'

[[applications]]
name = 'Blender'
method = 'winget'
id = 'BlenderFoundation.Blender'

[[applications]]
name = 'Visual Studio Code'
method = 'winget'
id = 'Microsoft.VisualStudioCode'

[[applications]]
name = 'Visual Studio Community'
method = 'manual'
site = 'https://visualstudio.microsoft.com/downloads/'

[[applications]]
name = 'GNU Octave'
method = 'winget'
id = 'GNU.Octave'

[[applications]]
name = 'CMake'
method = 'winget'
id = 'Kitware.CMake'

[[applications]]
name = 'Doxygen'
method = 'winget'
id = 'DimitriVanHeesch.Doxygen'

# Must appear after CMake and Doxygen because PATH order.
[[applications]]
# Include GNU Compiler Collection.
name = 'Perl'
method = 'winget'
id = 'StrawberryPerl.StrawberryPerl'

[[applications]]
name = 'Oh My Posh'
method = 'winget'
id = 'JanDeDobbeleer.OhMyPosh'

[[applications]]
name = 'Xmake'
method = 'winget'
id = 'Xmake-io.Xmake'

[[applications]]
name = 'Recuva'
method = 'winget'
id = 'Piriform.Recuva'
