# Applications that need to be installed.
#
# name = the name of the application.
# method = one of ['automatic', 'manual', 'winget'].
# - automatic = automatically download and try automatic installation.
#   - url = the URL download the file directly.
#   - args = install arguments.
# - manual = manual download and installation.
#   - site = the download site at which the browser opens.
# - winget = download and install using winget.
#   - id = the ID of the application in winget.

# Code

[[apps]]
name = 'NASM'
method = 'winget'
id = 'NASM.NASM'

[[apps]]
name = 'BF'
method = 'winget'
id = 'ChenQingYu.BF' # I contributed

# Include GNU Compiler Collection
[[apps]]
name = 'Perl'
method = 'winget'
id = 'StrawberryPerl.StrawberryPerl'

[[apps]]
name = 'D'
method = 'winget'
id = 'Dlang.DMD'

[[apps]]
name = 'Erlang'
method = 'winget'
id = 'Erlang.ErlangOTP'

[[apps]]
name = 'Elixir'
method = 'manual'
site = 'https://elixir-lang.org/install.html#windows'

[[apps]]
name = 'Haskell'
method = 'manual'
site = 'https://www.haskell.org/ghcup/'

[[apps]]
name = 'Java'
method = 'winget'
id = 'Oracle.JDK.21' # may need check the latest version

[[apps]]
name = 'JavaScript'
method = 'winget'
id = 'OpenJS.NodeJS.LTS'

[[apps]]
name = 'Lua'
method = 'winget'
id = 'DEVCOM.Lua'

[[apps]]
name = 'GNU Octave'
method = 'winget'
id = 'GNU.Octave'

[[apps]]
name = 'Mathematica'
method = 'winget'
id = 'WolframResearch.WolframEngine'

[[apps]]
name = 'NetLogo'
method = 'winget'
id = 'CCL.NetLogo'

[[apps]]
name = 'Prolog'
method = 'winget'
id = 'SWI-Prolog.SWI-Prolog'

[[apps]]
name = 'Ruby'
method = 'winget'
id = 'RubyInstallerTeam.RubyWithDevKit.3.2' # may need check the latest version

[[apps]]
name = 'Racket'
method = 'winget'
id = 'Racket.Racket'

[[apps]]
name = 'Rust'
method = 'winget'
id = 'Rustlang.Rustup'

[[apps]]
name = 'Standard ML'
method = 'winget'
id = 'SMLNJ.SMLNJ.Legacy' # I issued

[[apps]]
name = 'SQL'
method = 'winget'
id = 'SQLite.SQLite'

[[apps]]
name = 'TeX'
method = 'winget'
id = 'MiKTeX.MiKTeX'

[[apps]]
name = 'Typst'
method = 'winget'
id = 'Typst.Typst'

[[apps]]
name = 'Verilog'
method = 'winget'
id = 'Icarus.Verilog' # I issued

[[apps]]
name = 'Sublime Text'
method = 'winget'
id = 'SublimeHQ.SublimeText.4'

[[apps]]
name = 'Visual Studio Code'
method = 'winget'
id = 'Microsoft.VisualStudioCode'

[[apps]]
name = 'Visual Studio Community'
method = 'manual'
site = 'https://visualstudio.microsoft.com/downloads/'

[[apps]]
name = 'Toolbox App'
method = 'winget'
id = 'JetBrains.Toolbox'

[[apps]]
name = 'Qt'
method = 'automatic'
url = 'https://mirror.nju.edu.cn/qt/official_releases/online_installers/qt-unified-windows-x64-online.exe'
args = '--mirror https://mirror.nju.edu.cn/qt'

[[apps]]
name = 'Unity Hub'
method = 'winget'
id = 'Unity.UnityHub'

[[apps]]
name = 'SQLiteStudio'
method = 'winget'
id = 'sqlitestudio.pl.SQLiteStudio'

[[apps]]
name = 'Git'
method = 'winget'
id = 'Git.Git'

[[apps]]
name = 'Xmake'
method = 'winget'
id = 'Xmake-io.Xmake'

[[apps]]
name = 'Doxygen'
method = 'winget'
id = 'DimitriVanHeesch.Doxygen'

[[apps]]
name = 'Oh My Posh'
method = 'winget'
id = 'JanDeDobbeleer.OhMyPosh'

[[apps]]
name = 'Dr. Memory'
method = 'winget'
id = 'DynamoRIO.drmemory'

[[apps]]
name = 'Zeal'
method = 'winget'
id = 'OlegShparber.Zeal'

[[apps]]
name = 'Inno Setup'
method = 'winget'
id = 'JRSoftware.InnoSetup'

[[apps]]
name = 'Wireshark'
method = 'winget'
id = 'WiresharkFoundation.Wireshark'

[[apps]]
name = 'HxD'
method = 'winget'
id = 'MHNexus.HxD'

[[apps]]
name = 'Graphviz'
method = 'winget'
id = 'Graphviz.Graphviz'

[[apps]]
name = 'Sourcetrail'
method = 'winget'
id = 'CoatiSoftware.Sourcetrail' # I issued

[[apps]]
name = 'UMLet'
method = 'manual'
site = 'https://www.umlet.com/changes.htm'

[[apps]]
name = 'x64dbg'
method = 'manual'
site = 'https://github.com/x64dbg/x64dbg/releases'

[[apps]]
name = 'Komac'
method = 'winget'
id = 'RussellBanks.Komac'

# Tool

[[apps]]
name = 'Bandizip'
method = 'winget'
id = 'Bandisoft.Bandizip'

[[apps]]
name = 'Blender'
method = 'winget'
id = 'BlenderFoundation.Blender'

[[apps]]
name = 'Recuva'
method = 'winget'
id = 'Piriform.Recuva'

[[apps]]
name = 'VirtualBox'
method = 'winget'
id = 'Oracle.VirtualBox'

[[apps]]
name = 'Google Earth'
method = 'winget'
id = 'Google.EarthPro'

[[apps]]
name = 'qBittorrent'
method = 'winget'
id = 'qBittorrent.qBittorrent'

[[apps]]
name = 'calibre'
method = 'winget'
id = 'calibre.calibre'

[[apps]]
name = '网易云音乐'
method = 'winget'
id = 'NetEase.CloudMusic'

[[apps]]
name = 'Free Download Manager'
method = 'winget'
id = 'SoftDeluxe.FreeDownloadManager'

[[apps]]
name = 'WinMerge'
method = 'winget'
id = 'WinMerge.WinMerge'

[[apps]]
name = 'GeoGebra'
method = 'winget'
id = 'GeoGebra.Classic'

[[apps]]
name = '百度网盘'
method = 'winget'
id = 'Baidu.BaiduNetdisk'

[[apps]]
name = 'QQ'
method = 'winget'
id = 'Tencent.QQ'

[[apps]]
name = '微信'
method = 'winget'
id = 'Tencent.WeChat'

[[apps]]
name = '腾讯会议'
method = 'winget'
id = 'Tencent.TencentMeeting'

[[apps]]
name = 'RustDesk'
method = 'winget'
id = 'RustDesk.RustDesk'

[[apps]]
name = 'PotPlayer'
method = 'winget'
id = 'Daum.PotPlayer'

[[apps]]
name = 'Honeyview'
method = 'winget'
id = 'Bandisoft.Honeyview'

[[apps]]
name = 'Snipaste'
method = 'manual'
site = 'https://www.snipaste.com/download.html'

[[apps]]
name = 'EV录屏'
method = 'manual'
site = 'https://www.ieway.cn/evcapture.html'

[[apps]]
name = 'FreePiano'
method = 'manual'
site = 'https://freepiano.tiwb.com/cn/'

[[apps]]
name = 'TrafficMonitor'
method = 'manual'
site = 'https://github.com/zhongyang219/TrafficMonitor/releases'

# Game

[[apps]]
name = '仙剑奇侠传四'
method = 'manual'
site = 'http://pal4.roogames.com/pal4/download/'

[[apps]]
name = 'Golly'
method = 'manual'
site = 'https://sourceforge.net/projects/golly/files/'

[[apps]]
name = '孤独に効く百合'
method = 'manual'
site = 'https://store.steampowered.com/app/800120/Lonely_Yuri/'

[[apps]]
name = 'SpaceEngine'
method = 'manual'
site = 'https://store.steampowered.com/app/314650/SpaceEngine/'

[[apps]]
name = 'ENDER LILIES: Quietus of the Knights'
method = 'manual'
site = 'https://store.steampowered.com/app/1369630/ENDER_LILIES_Quietus_of_the_Knights/'

[[apps]]
name = 'Ballex'
method = 'manual'
site = 'https://store.steampowered.com/app/1114430/Ballex/'

[[apps]]
name = 'Dark Souls Ⅲ'
method = 'manual'
site = 'https://store.steampowered.com/app/374320/DARK_SOULS_III/'

[[apps]]
name = '0 A.D.'
method = 'manual'
site = 'https://play0ad.com/download/win/'
