# List of git repositories.
#
# path = the path of the local repository.
# remote = remote repository addresses.
# upstream = the upstream remote repository host.

[[repos]]
path = 'E:/Project/automation'
remote = { github = 'https://github.com/chen-qingyu/automation.git', gitee = 'https://gitee.com/ChobitsY/automation.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/pyinrs'
remote = { github = 'https://github.com/chen-qingyu/pyinrs.git', gitee = 'https://gitee.com/ChobitsY/pyinrs.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/pyincpp'
remote = { github = 'https://github.com/chen-qingyu/pyincpp.git', gitee = 'https://gitee.com/ChobitsY/pyincpp.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/mymatrix'
remote = { github = 'https://github.com/chen-qingyu/mymatrix.git', gitee = 'https://gitee.com/ChobitsY/mymatrix.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/hellods'
remote = { github = 'https://github.com/chen-qingyu/hellods.git', gitee = 'https://gitee.com/ChobitsY/hellods.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/hello-world'
remote = { github = 'https://github.com/chen-qingyu/hello-world.git', gitee = 'https://gitee.com/ChobitsY/hello-world.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/bad-apple'
remote = { github = 'https://github.com/chen-qingyu/bad-apple', gitee = 'https://gitee.com/ChobitsY/bad-apple' }
upstream = 'github'

[[repos]]
path = 'E:/Project/bf'
remote = { github = 'https://github.com/chen-qingyu/bf', gitee = 'https://gitee.com/ChobitsY/bf' }
upstream = 'github'

[[repos]]
path = 'E:/Project/code-base'
remote = { github = 'https://github.com/chen-qingyu/code-base.git', gitee = 'https://gitee.com/ChobitsY/code-base.git' }
upstream = 'github'

[[repos]]
path = 'E:/Study/answer-cprimerplus'
remote = { github = 'https://github.com/chen-qingyu/answer-cprimerplus.git', gitee = 'https://gitee.com/ChobitsY/answer-cprimerplus.git' }
upstream = 'github'

[[repos]]
path = 'E:/Study/answer-ostep'
remote = { github = 'https://github.com/chen-qingyu/answer-ostep.git', gitee = 'https://gitee.com/ChobitsY/answer-ostep.git' }
upstream = 'github'

[[repos]]
path = 'E:/Study/answer-htdp'
remote = { github = 'https://github.com/chen-qingyu/answer-htdp.git', gitee = 'https://gitee.com/ChobitsY/answer-htdp.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/hexo-markdown-image'
remote = { github = 'https://github.com/chen-qingyu/hexo-markdown-image' }
upstream = 'github'

[[repos]]
path = 'E:/Project/hexo-console-zhihu'
remote = { github = 'https://github.com/chen-qingyu/hexo-console-zhihu.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/hexo-theme-diaspora'
remote = { github = 'https://github.com/chen-qingyu/hexo-theme-diaspora.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/mathagape'
remote = { gitee = 'https://gitee.com/ChobitsY/mathagape.git' }
upstream = 'gitee'

[[repos]]
path = 'E:/Project/sand-box'
remote = { gitee = 'https://gitee.com/ChobitsY/sand-box.git' }
upstream = 'gitee'
