# List of environment configurations.
# You may need to use `winget install --id Python.Python.3.12` first.
# You may need to use https://mirrors.ustc.edu.cn/ if something wrong with downloading.

# Python third-party libraries that need to be installed/upgraded.
libraries = [
    'numpy',
    'scipy',
    'sympy',

    'matplotlib',
    'pillow',     # PIL
    # 'jupyter',

    'pyinstaller',
    'pygame',
    'pyautogui',
    'pyserial',    # serial

    # 'wordcloud',
    # 'jieba',

    'requests',
    'beautifulsoup4', # bs4

    'opencv-python', # cv2, name conflicts with easyocr's dep: opencv-python-headless
    # 'tensorflow', # the latest version conflicts with numpy

    'autopep8',
    'ipython',

    'colorama',
    'tqdm',

    'PySide6',

    'graph-tools',
    'objprint',
    'viztracer',

    'django',
    'djlint',
]

# Applications that need to be installed.
#
# name = the name of the application.
# method = one of ['automatic', 'manual', 'winget'].
# - automatic = automatically download and try automatic installation.
#   - url = the URL download the file directly.
#   - args = install arguments.
# - manual = manual download and installation.
#   - site = the download site at which the browser opens.
# - winget = download and install using winget.
#   - id = the ID of the application in winget.

[[applications]]
name = 'Qt'
method = 'automatic'
url = 'https://mirror.nju.edu.cn/qt/official_releases/online_installers/qt-unified-windows-x64-online.exe'
args = '--mirror https://mirror.nju.edu.cn/qt'

[[applications]]
name = 'Sublime Text'
method = 'winget'
id = 'SublimeHQ.SublimeText.4'

[[applications]]
name = 'Bandizip'
method = 'winget'
id = 'Bandisoft.Bandizip'

[[applications]]
name = 'Android Studio'
method = 'winget'
id = 'Google.AndroidStudio'

[[applications]]
name = 'Git'
method = 'winget'
id = 'Git.Git'

[[applications]]
name = 'Sourcetrail'
method = 'manual'
site = 'https://github.com/CoatiSoftware/Sourcetrail/releases'

[[applications]]
name = 'Blender'
method = 'winget'
id = 'BlenderFoundation.Blender'

[[applications]]
name = 'Visual Studio Code'
method = 'winget'
id = 'Microsoft.VisualStudioCode'

[[applications]]
name = 'Visual Studio Community'
method = 'manual'
site = 'https://visualstudio.microsoft.com/downloads/'

[[applications]]
name = 'Oh My Posh'
method = 'winget'
id = 'JanDeDobbeleer.OhMyPosh'

[[applications]]
name = 'Xmake'
method = 'winget'
id = 'Xmake-io.Xmake'

[[applications]]
name = 'Recuva'
method = 'winget'
id = 'Piriform.Recuva'

# Include GNU Compiler Collection, CMake, Doxygen, NASM.
[[applications]]
name = 'Perl'
method = 'winget'
id = 'StrawberryPerl.StrawberryPerl'

[[applications]]
name = 'D'
method = 'winget'
id = 'Dlang.DMD'

[[applications]]
name = 'Erlang'
method = 'winget'
id = 'Erlang.ErlangOTP'

[[applications]]
name = 'Elixir'
method = 'manual'
site = 'https://elixir-lang.org/install.html#windows'

[[applications]]
name = 'Haskell'
method = 'manual'
site = 'https://www.haskell.org/ghcup/'

[[applications]]
name = 'Java'
method = 'winget'
id = 'Oracle.JDK.21' # may need check the latest version

[[applications]]
name = 'JavaScript'
method = 'winget'
id = 'OpenJS.NodeJS.LTS'

[[applications]]
name = 'Lua'
method = 'winget'
id = 'DEVCOM.Lua'

[[applications]]
name = 'GNU Octave'
method = 'winget'
id = 'GNU.Octave'

[[applications]]
name = 'Mathematica'
method = 'winget'
id = 'WolframResearch.WolframEngine'

[[applications]]
name = 'NetLogo'
method = 'winget'
id = 'CCL.NetLogo'

[[applications]]
name = 'Prolog'
method = 'winget'
id = 'SWI-Prolog.SWI-Prolog'

[[applications]]
name = 'Ruby'
method = 'winget'
id = 'RubyInstallerTeam.RubyWithDevKit.3.2' # may need check the latest version

[[applications]]
name = 'Racket'
method = 'winget'
id = 'Racket.Racket'

[[applications]]
name = 'Rust'
method = 'winget'
id = 'Rustlang.Rustup'

[[applications]]
name = 'Standard ML'
method = 'manual'
site = 'https://www.smlnj.org/index.html'

[[applications]]
name = 'SQL'
method = 'winget'
id = 'SQLite.SQLite'

[[applications]]
name = 'SQLiteStudio'
method = 'winget'
id = 'sqlitestudio.pl.SQLiteStudio'

[[applications]]
name = 'TeX'
method = 'winget'
id = 'MiKTeX.MiKTeX'

[[applications]]
name = 'TeXstudio'
method = 'winget'
id = 'TeXstudio.TeXstudio'

[[applications]]
name = 'Verilog'
method = 'manual'
site = 'https://bleyer.org/icarus/'
