# List of git repositories.
#
# path = the path of the local repository.
# remote = remote repository addresses.
# upstream = the upstream remote repository host.

[[repos]]
path = 'F:/Automation'
remote = { github = 'https://github.com/chen-qingyu/Automation.git', gitee = 'https://gitee.com/ChobitsY/automation.git' }
upstream = 'github'

[[repos]]
path = 'F:/Projects/pyinrs'
remote = { github = 'https://github.com/chen-qingyu/pyinrs.git', gitee = 'https://gitee.com/ChobitsY/pyinrs.git' }
upstream = 'github'

[[repos]]
path = 'F:/Projects/pyincpp'
remote = { github = 'https://github.com/chen-qingyu/pyincpp.git', gitee = 'https://gitee.com/ChobitsY/pyincpp.git' }
upstream = 'github'

[[repos]]
path = 'F:/Projects/mymatrix'
remote = { github = 'https://github.com/chen-qingyu/mymatrix.git', gitee = 'https://gitee.com/ChobitsY/mymatrix.git' }
upstream = 'github'

[[repos]]
path = 'F:/Projects/HelloWorld'
remote = { github = 'https://github.com/chen-qingyu/HelloWorld.git', gitee = 'https://gitee.com/ChobitsY/HelloWorld.git' }
upstream = 'github'

[[repos]]
path = 'F:/Projects/HelloDataStructure'
remote = { github = 'https://github.com/chen-qingyu/HelloDataStructure.git', gitee = 'https://gitee.com/ChobitsY/HelloDataStructure.git' }
upstream = 'github'

[[repos]]
path = 'F:/Projects/BadApple'
remote = { github = 'https://github.com/chen-qingyu/BadApple', gitee = 'https://gitee.com/ChobitsY/BadApple' }
upstream = 'github'

[[repos]]
path = 'F:/Projects/bfi'
remote = { github = 'https://github.com/chen-qingyu/bfi', gitee = 'https://gitee.com/ChobitsY/bfi' }
upstream = 'github'

[[repos]]
path = 'F:/Code/C'
remote = { github = 'https://github.com/chen-qingyu/C-Code.git', gitee = 'https://gitee.com/ChobitsY/C-Code.git' }
upstream = 'github'

[[repos]]
path = 'F:/Code/Python'
remote = { github = 'https://github.com/chen-qingyu/Python-Code.git', gitee = 'https://gitee.com/ChobitsY/Python-Code.git' }
upstream = 'github'

[[repos]]
path = 'F:/Code/STM32'
remote = { github = 'https://github.com/chen-qingyu/STM32-Code.git', gitee = 'https://gitee.com/ChobitsY/STM32-Code.git' }
upstream = 'github'

[[repos]]
path = 'F:/Code/TeX'
remote = { github = 'https://github.com/chen-qingyu/TeX-Code.git', gitee = 'https://gitee.com/ChobitsY/TeX-Code.git' }
upstream = 'github'

[[repos]]
path = 'F:/Code/Typst'
remote = { github = 'https://github.com/chen-qingyu/Typst-Code.git', gitee = 'https://gitee.com/ChobitsY/Typst-Code.git' }
upstream = 'github'

[[repos]]
path = 'F:/Learn/C Primer Plus'
remote = { github = 'https://github.com/chen-qingyu/C-Primer-Plus.git', gitee = 'https://gitee.com/ChobitsY/c-primer-plus.git' }
upstream = 'github'

[[repos]]
path = 'F:/Learn/OSTEP'
remote = { github = 'https://github.com/chen-qingyu/OSTEP.git', gitee = 'https://gitee.com/ChobitsY/ostep.git' }
upstream = 'github'

[[repos]]
path = 'F:/Learn/HtDP'
remote = { github = 'https://github.com/chen-qingyu/HtDP.git', gitee = 'https://gitee.com/ChobitsY/htdp.git' }
upstream = 'github'
