# List of git repositories.
#
# path = the path of the local repository.
# remote = remote repository addresses.
# upstream = the upstream remote repository host.

[[repos]]
path = 'E:/Automation'
remote = { github = 'https://github.com/chen-qingyu/Automation.git', gitee = 'https://gitee.com/ChobitsY/automation.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/pyinrs'
remote = { github = 'https://github.com/chen-qingyu/pyinrs.git', gitee = 'https://gitee.com/ChobitsY/pyinrs.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/pyincpp'
remote = { github = 'https://github.com/chen-qingyu/pyincpp.git', gitee = 'https://gitee.com/ChobitsY/pyincpp.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/mymatrix'
remote = { github = 'https://github.com/chen-qingyu/mymatrix.git', gitee = 'https://gitee.com/ChobitsY/mymatrix.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/hellods'
remote = { github = 'https://github.com/chen-qingyu/hellods.git', gitee = 'https://gitee.com/ChobitsY/hellods.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/HelloWorld'
remote = { github = 'https://github.com/chen-qingyu/HelloWorld.git', gitee = 'https://gitee.com/ChobitsY/HelloWorld.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/BadApple'
remote = { github = 'https://github.com/chen-qingyu/BadApple', gitee = 'https://gitee.com/ChobitsY/BadApple' }
upstream = 'github'

[[repos]]
path = 'E:/Project/bf'
remote = { github = 'https://github.com/chen-qingyu/bf', gitee = 'https://gitee.com/ChobitsY/bf' }
upstream = 'github'

[[repos]]
path = 'E:/CodeBase'
remote = { github = 'https://github.com/chen-qingyu/CodeBase.git', gitee = 'https://gitee.com/ChobitsY/code-base.git' }
upstream = 'github'

[[repos]]
path = 'E:/Exercise/C Primer Plus'
remote = { github = 'https://github.com/chen-qingyu/C-Primer-Plus.git', gitee = 'https://gitee.com/ChobitsY/c-primer-plus.git' }
upstream = 'github'

[[repos]]
path = 'E:/Exercise/OSTEP'
remote = { github = 'https://github.com/chen-qingyu/OSTEP.git', gitee = 'https://gitee.com/ChobitsY/ostep.git' }
upstream = 'github'

[[repos]]
path = 'E:/Exercise/HtDP'
remote = { github = 'https://github.com/chen-qingyu/HtDP.git', gitee = 'https://gitee.com/ChobitsY/htdp.git' }
upstream = 'github'
