# List of git repositories.
#
# path = the path of the local repository.
# remote = remote repository addresses.
# upstream = the upstream remote repository host.

[[repos]]
path = 'E:/Project/automation'
remote = { github = 'https://github.com/chen-qingyu/automation.git', gitee = 'https://gitee.com/chobitsy/automation.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/pyincpp'
remote = { github = 'https://github.com/chen-qingyu/pyincpp.git', gitee = 'https://gitee.com/chobitsy/pyincpp.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/pyinrs'
remote = { github = 'https://github.com/chen-qingyu/pyinrs.git', gitee = 'https://gitee.com/chobitsy/pyinrs.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/hellods'
remote = { github = 'https://github.com/chen-qingyu/hellods.git', gitee = 'https://gitee.com/chobitsy/hellods.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/mymatrix'
remote = { github = 'https://github.com/chen-qingyu/mymatrix.git', gitee = 'https://gitee.com/chobitsy/mymatrix.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/code-base'
remote = { github = 'https://github.com/chen-qingyu/code-base.git', gitee = 'https://gitee.com/chobitsy/code-base.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/hello-world'
remote = { github = 'https://github.com/chen-qingyu/hello-world.git', gitee = 'https://gitee.com/chobitsy/hello-world.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/bf'
remote = { github = 'https://github.com/chen-qingyu/bf', gitee = 'https://gitee.com/chobitsy/bf' }
upstream = 'github'

[[repos]]
path = 'E:/Project/flags'
remote = { github = 'https://github.com/chen-qingyu/flags' }
upstream = 'github'

[[repos]]
path = 'E:/Project/greek-char'
remote = { github = 'https://github.com/chen-qingyu/greek-char' }
upstream = 'github'

[[repos]]
path = 'E:/Project/bad-apple'
remote = { github = 'https://github.com/chen-qingyu/bad-apple', gitee = 'https://gitee.com/chobitsy/bad-apple' }
upstream = 'github'

[[repos]]
path = 'E:/Blog/my-blog'
remote = { github = 'https://github.com/chen-qingyu/chen-qingyu.github.io.git' }
upstream = 'github'

[[repos]]
path = 'E:/Study/Answer C Primer Plus'
remote = { github = 'https://github.com/chen-qingyu/answer-cprimerplus.git', gitee = 'https://gitee.com/chobitsy/answer-cprimerplus.git' }
upstream = 'github'

[[repos]]
path = 'E:/Study/Answer OSTEP'
remote = { github = 'https://github.com/chen-qingyu/answer-ostep.git', gitee = 'https://gitee.com/chobitsy/answer-ostep.git' }
upstream = 'github'

[[repos]]
path = 'E:/Study/Answer HtDP'
remote = { github = 'https://github.com/chen-qingyu/answer-htdp.git', gitee = 'https://gitee.com/chobitsy/answer-htdp.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/hexo-markdown-image'
remote = { github = 'https://github.com/chen-qingyu/hexo-markdown-image' }
upstream = 'github'

[[repos]]
path = 'E:/Project/hexo-console-zhihu'
remote = { github = 'https://github.com/chen-qingyu/hexo-console-zhihu.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/semmath'
remote = { github = 'https://github.com/semmath/semmath.git' }
upstream = 'github'

[[repos]]
path = 'E:/Project/mathagape'
remote = { gitee = 'https://gitee.com/chobitsy/mathagape.git' }
upstream = 'gitee'

[[repos]]
path = 'E:/Project/sand-box'
remote = { gitee = 'https://gitee.com/chobitsy/sand-box.git' }
upstream = 'gitee'
