# List of environment configurations

# Python third-party libraries that need to be installed/upgraded
libraries = [
    'numpy',
    'scipy',
    'sympy',

    'matplotlib',
    'pillow',     # PIL

    'pyinstaller',
    'pygame',
    'pyautogui',
    'pyserial',    # serial

    # 'wordcloud',
    # 'jieba',

    'requests',
    'beautifulsoup4', # bs4

    'opencv-python', # cv2, name conflicts with easyocr's dep: opencv-python-headless

    # 'tensorflow', # the latest version conflicts with numpy

    'jupyter',

    'autopep8',

    'colorama',

    # 'PySide6',
    'PyQt6',

    'graph-tools',

    'objprint',
    'viztracer',

    'django',
    'djlint',

    'git-archive-all',

    'tqdm',
]

# Applications that need to be installed

# name: the name of the application
# method: one of ['automatic', 'manual', 'winget']
# - automatic: automatically download and try automatic installation
#   - download_url: the URL download the file directly
#   - install_args: install arguments
# - manual: manual download and installation
#   - download_link: the download link at which the browser opens
# - winget: download and install using winget
#   - id: the ID of the application in winget

[[applications]]
name = 'Qt'
method = 'automatic'
download_url = 'https://mirror.nju.edu.cn/qt/official_releases/online_installers/qt-unified-windows-x64-online.exe'
install_args = '--mirror https://mirror.nju.edu.cn/qt'

[[applications]]
name = 'Sublime Text'
method = 'manual'
download_link = 'https://www.sublimetext.com/download_thanks?target=win-x64'

[[applications]]
name = 'Bandizip'
method = 'manual'
download_link = 'https://www.bandisoft.com/bandizip/dl.php?web'

[[applications]]
name = 'Android Studio'
method = 'manual'
download_link = 'https://developer.android.com/studio'

[[applications]]
name = 'Git'
method = 'winget'
id = 'Git.Git'
