# List of environment configurations.
# You may need to use `winget install --id Python.Python.3.12` first.
# You may need to use https://mirrors.ustc.edu.cn/ if something wrong with downloading.

# Python third-party libraries that need to be installed/upgraded.
libraries = [
    'numpy',
    'scipy',
    'sympy',

    'matplotlib',
    'pillow',     # PIL
    # 'jupyter',

    'pyinstaller',
    'pygame',
    'pyautogui',
    'pyserial',    # serial

    # 'wordcloud',
    # 'jieba',

    'requests',
    'beautifulsoup4', # bs4

    'opencv-python', # cv2, name conflicts with easyocr's dep: opencv-python-headless
    # 'tensorflow', # the latest version conflicts with numpy

    'autopep8',
    'ipython',

    'colorama',
    'tqdm',

    'PySide6',

    'graph-tools',
    'objprint',
    'viztracer',

    # 'django',
    # 'djlint',
]

# Applications that need to be installed.
#
# name = the name of the application.
# method = one of ['automatic', 'manual', 'winget'].
# - automatic = automatically download and try automatic installation.
#   - url = the URL download the file directly.
#   - args = install arguments.
# - manual = manual download and installation.
#   - site = the download site at which the browser opens.
# - winget = download and install using winget.
#   - id = the ID of the application in winget.

[[applications]]
name = 'Qt'
method = 'automatic'
url = 'https://mirror.nju.edu.cn/qt/official_releases/online_installers/qt-unified-windows-x64-online.exe'
args = '--mirror https://mirror.nju.edu.cn/qt'

[[applications]]
name = 'Sublime Text'
method = 'winget'
id = 'SublimeHQ.SublimeText.4'

[[applications]]
name = 'Bandizip'
method = 'winget'
id = 'Bandisoft.Bandizip'

[[applications]]
name = 'Android Studio'
method = 'winget'
id = 'Google.AndroidStudio'

[[applications]]
name = 'Git'
method = 'winget'
id = 'Git.Git'

[[applications]]
name = 'Sourcetrail'
method = 'manual'
site = 'https://github.com/CoatiSoftware/Sourcetrail/releases'

[[applications]]
name = 'Blender'
method = 'winget'
id = 'BlenderFoundation.Blender'

[[applications]]
name = 'Visual Studio Code'
method = 'winget'
id = 'Microsoft.VisualStudioCode'

[[applications]]
name = 'Visual Studio Community'
method = 'manual'
site = 'https://visualstudio.microsoft.com/downloads/'

[[applications]]
name = 'Oh My Posh'
method = 'winget'
id = 'JanDeDobbeleer.OhMyPosh'

[[applications]]
name = 'Xmake'
method = 'winget'
id = 'Xmake-io.Xmake'

[[applications]]
name = 'Recuva'
method = 'winget'
id = 'Piriform.Recuva'

[[applications]]
name = 'Doxygen'
method = 'winget'
id = 'DimitriVanHeesch.Doxygen'

[[applications]]
name = 'Unity Hub'
method = 'winget'
id = 'Unity.UnityHub'

[[applications]]
name = 'Dr. Memory'
method = 'winget'
id = 'DynamoRIO.drmemory'

[[applications]]
name = 'Wireshark'
method = 'winget'
id = 'WiresharkFoundation.Wireshark'

[[applications]]
name = 'VirtualBox'
method = 'winget'
id = 'Oracle.VirtualBox'

[[applications]]
name = 'Zeal'
method = 'winget'
id = 'OlegShparber.Zeal'

[[applications]]
name = 'Google Earth'
method = 'winget'
id = 'Google.EarthPro'

[[applications]]
name = 'qBittorrent'
method = 'winget'
id = 'qBittorrent.qBittorrent'

[[applications]]
name = 'calibre'
method = 'winget'
id = 'calibre.calibre'

[[applications]]
name = 'Inno Setup'
method = 'winget'
id = 'JRSoftware.InnoSetup'

[[applications]]
name = '网易云音乐'
method = 'winget'
id = 'NetEase.CloudMusic'

[[applications]]
name = 'UMLet'
method = 'manual'
site = 'https://www.umlet.com/changes.htm'

[[applications]]
name = 'Free Download Manager'
method = 'winget'
id = 'SoftDeluxe.FreeDownloadManager'

[[applications]]
name = 'WinMerge'
method = 'winget'
id = 'WinMerge.WinMerge'

[[applications]]
name = 'GeoGebra'
method = 'winget'
id = 'GeoGebra.Classic'

[[applications]]
name = '百度网盘'
method = 'winget'
id = 'Baidu.BaiduNetdisk'

[[applications]]
name = '仙剑奇侠传四'
method = 'manual'
site = 'http://pal4.roogames.com/pal4/download/'

[[applications]]
name = 'Golly'
method = 'manual'
site = 'https://sourceforge.net/projects/golly/files/'

[[applications]]
name = '孤独に効く百合'
method = 'manual'
site = 'https://store.steampowered.com/app/800120/Lonely_Yuri/'

[[applications]]
name = 'SpaceEngine'
method = 'manual'
site = 'https://store.steampowered.com/app/314650/SpaceEngine/'

[[applications]]
name = 'ENDER LILIES: Quietus of the Knights'
method = 'manual'
site = 'https://store.steampowered.com/app/1369630/ENDER_LILIES_Quietus_of_the_Knights/'

[[applications]]
name = 'Ballex'
method = 'manual'
site = 'https://store.steampowered.com/app/1114430/Ballex/'

[[applications]]
name = 'Dark Souls Ⅲ'
method = 'manual'
site = 'https://store.steampowered.com/app/374320/DARK_SOULS_III/'

[[applications]]
name = '0 A.D.'
method = 'manual'
site = 'https://play0ad.com/download/win/'

[[applications]]
name = 'QQ'
method = 'winget'
id = 'Tencent.QQ'

[[applications]]
name = '微信'
method = 'winget'
id = 'Tencent.WeChat'

[[applications]]
name = '腾讯会议'
method = 'winget'
id = 'Tencent.TencentMeeting'

[[applications]]
name = 'RustDesk'
method = 'winget'
id = 'RustDesk.RustDesk'

[[applications]]
name = 'PotPlayer'
method = 'winget'
id = 'Daum.PotPlayer'

[[applications]]
name = 'Honeyview'
method = 'winget'
id = 'Bandisoft.Honeyview'

[[applications]]
name = 'Snipaste'
method = 'manual'
site = 'https://www.snipaste.com/download.html'

[[applications]]
name = 'EV录屏'
method = 'manual'
site = 'https://www.ieway.cn/evcapture.html'

[[applications]]
name = 'FreePiano'
method = 'manual'
site = 'https://freepiano.tiwb.com/cn/'

[[applications]]
name = 'Graphviz'
method = 'winget'
id = 'Graphviz.Graphviz'

[[applications]]
name = 'TrafficMonitor'
method = 'manual'
site = 'https://github.com/zhongyang219/TrafficMonitor/releases'

[[applications]]
name = 'x64dbg'
method = 'manual'
site = 'https://github.com/x64dbg/x64dbg/releases'

[[applications]]
name = 'HxD'
method = 'winget'
id = 'MHNexus.HxD'

[[applications]]
name = 'NASM'
method = 'winget'
id = 'NASM.NASM'

# Include GNU Compiler Collection, CMake, Doxygen, NASM.
[[applications]]
name = 'Perl'
method = 'winget'
id = 'StrawberryPerl.StrawberryPerl'

[[applications]]
name = 'D'
method = 'winget'
id = 'Dlang.DMD'

[[applications]]
name = 'Erlang'
method = 'winget'
id = 'Erlang.ErlangOTP'

[[applications]]
name = 'Elixir'
method = 'manual'
site = 'https://elixir-lang.org/install.html#windows'

[[applications]]
name = 'Haskell'
method = 'manual'
site = 'https://www.haskell.org/ghcup/'

[[applications]]
name = 'Java'
method = 'winget'
id = 'Oracle.JDK.21' # may need check the latest version

[[applications]]
name = 'JavaScript'
method = 'winget'
id = 'OpenJS.NodeJS.LTS'

[[applications]]
name = 'Lua'
method = 'winget'
id = 'DEVCOM.Lua'

[[applications]]
name = 'GNU Octave'
method = 'winget'
id = 'GNU.Octave'

[[applications]]
name = 'Mathematica'
method = 'winget'
id = 'WolframResearch.WolframEngine'

[[applications]]
name = 'NetLogo'
method = 'winget'
id = 'CCL.NetLogo'

[[applications]]
name = 'Prolog'
method = 'winget'
id = 'SWI-Prolog.SWI-Prolog'

[[applications]]
name = 'Ruby'
method = 'winget'
id = 'RubyInstallerTeam.RubyWithDevKit.3.2' # may need check the latest version

[[applications]]
name = 'Racket'
method = 'winget'
id = 'Racket.Racket'

[[applications]]
name = 'Rust'
method = 'winget'
id = 'Rustlang.Rustup'

[[applications]]
name = 'Standard ML'
method = 'manual'
site = 'https://www.smlnj.org/index.html'

[[applications]]
name = 'SQL'
method = 'winget'
id = 'SQLite.SQLite'

[[applications]]
name = 'SQLiteStudio'
method = 'winget'
id = 'sqlitestudio.pl.SQLiteStudio'

[[applications]]
name = 'TeX'
method = 'winget'
id = 'MiKTeX.MiKTeX'

[[applications]]
name = 'TeXstudio'
method = 'winget'
id = 'TeXstudio.TeXstudio'

[[applications]]
name = 'Verilog'
method = 'manual'
site = 'https://bleyer.org/icarus/'
